In [1]:
import numpy as np

In [7]:
# in np.array, we need to use a list to present the data
a = np.array([1, 2, 3], dtype = np.int32) # and we can define the data type of array, (search data types in doc)
                                          # np.int16/32/64..., np.float32/64 (32 small number occupies smaller memory)
print(a.dtype) 
print(a)

int32
[1 2 3]


In [50]:
# create a matrix, like list of list [[ , , ], 
                                    # [ , , ], 
                                    # [ , , ]]
a = np.array([[1, 2, 3],
             [4, 5, 6]])
print(a)
print('')

# create all 0 matrix, need to define the shape
a = np.zeros((3, 4))
print(a)
print('')

# create all 1 matrix, need to define the shape
a = np.ones((3, 4), dtype = np.int16)
print(a)
print('')

# create empty matrix
a = np.empty((3,4))
print(a)
print('')

# create an ordered array/matrix
a = np.arange(10, 21, 2).reshape((3, 2))
# similar to range in python, starting and ending. if wnat to define shape, use reshape
print(a)
print('')

# create a linspace
a = np.linspace(1, 10, 6).reshape((2, 3)) # from 1 to 10, the line is divided into 6 pieces equally and automatically
print(a)

[[1 2 3]
 [4 5 6]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[10 12]
 [14 16]
 [18 20]]

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]
