In [1]:
import numpy as np

In [2]:
a = np.array([10, 20, 30, 40])
b = np.arange(4)

# subtraction, etc. (this is element operation)
c = a - b
print(c)
print('')

# trigonometric functions
c = 10 * np.sin(a)
print(c)
print('')

# comparator
print(b)
print(b < 3)

[10 19 28 37]

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]

[0 1 2 3]
[ True  True  True False]


In [3]:
# 2D matrix operation
a = np.array([[1, 1],
              [0, 1]])
b = np.arange(4).reshape(2,2)

print(a)
print('')

print(b)
print('')

#  element operation
c = a * b
print(c)
print('')

# matrix multiplication, not dot product or cross product
c = np.dot(a, b) # or a.dot(b)
print(c) 

# [[1 1]     [[0 1]    
#  [0 1]]     [2 3]]
 
# = [[1*0+1*2  1*1+1*3] = [[2 4]
#    [0*0+1*2  0*1+1*3]    [2 3]]

[[1 1]
 [0 1]]

[[0 1]
 [2 3]]

[[0 1]
 [0 3]]

[[2 4]
 [2 3]]


In [4]:
# create a random array
a = np.random.random((2, 4)) # each element is from 0 to 1
print(a)
print('')

# min, max, sum of the matrix
print(np.sum(a))
print('')

print(np.sum(a, axis = 1)) # axis = 1 find the sum row by row, 0 find the sum col by col
print('')

print(np.min(a, axis = 1)) # 1 min of each row, 0 min of each col
print('')

print(np.max(a, axis = 0)) # 1 min of each row, 0 min of each col

[[0.0235876  0.39450879 0.61998764 0.70097883]
 [0.32537019 0.61752178 0.51408958 0.29463672]]

3.490681133227681

[1.73906287 1.75161827]

[0.0235876  0.29463672]

[0.32537019 0.61752178 0.61998764 0.70097883]


In [5]:
a = np.arange(14, 2, -1).reshape(3, 4)
print(a)
print('')

# find the index of the min, max element in matrix
print(np.argmin(a))
print(np.argmax(a))
print('')

# mean value of matrix
print(np.mean(a))
print(a.mean()) # or this way, built-in method mean of numpy.ndarray
print(np.average(a)) # or this way
print('')

# median
print(np.median(a)) # axis = 1 median of each row, 0 median of each col
print('')

# accumulation sum
print(np.cumsum(a)) # default [2 2+3 2+3+4....]
print('')           # if axis = 0, row by row horizontally, 1 col by col vertically
    
# difference between each element
print(np.diff(a))
print('')

# find nonzero
print(np.nonzero(a)) # return the indices of the elements that are non-zero.
# so array 1 is row indices, array 2 is col indices

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]

11
0

8.5
8.5
8.5

8.5

[ 14  27  39  50  60  69  77  84  90  95  99 102]

[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


In [6]:
# sort the matrix
a = np.sort(a)
print(a)
print('')

# transpose
print(np.transpose(a))
print('')

# transpose mutliplicates nontranspose, not element multiplication
c = (a.T).dot(a)
print(c)

[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]

[[11  7  3]
 [12  8  4]
 [13  9  5]
 [14 10  6]]

[[179 200 221 242]
 [200 224 248 272]
 [221 248 275 302]
 [242 272 302 332]]


In [11]:
a = np.arange(2, 14).reshape(3, 4)
print(a)
a = np.clip(a, 5, 10) # return an array whose values are limited to [min, max]
print(a)              # the vlaue < 5 will become 5, > 10 will become 10

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[ 5  5  5  5]
 [ 6  7  8  9]
 [10 10 10 10]]
