In [1]:
import numpy as np

In [51]:
# indexing in 1D
a = np.arange(14, 30)
print(a)
# indexing the element in 1D
print(a[3])
print('')

# indexing in 2D
a = np.arange(14, 30).reshape(4,4)
print(a)
# indexing the row in 2D
print(a[3])
# indexing the element in 2D
print(a[3][2])
print(a[3, 2]) # or this way
# indexing all element in row or col
print(a[3, :])
print(a[:, 2])

[14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
17

[[14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]]
[26 27 28 29]
28
28
[26 27 28 29]
[16 20 24 28]


In [52]:
# output each row / col in matrix with loop
for row in a: # the iteration is the row of a
    print(row)
print('')

for col in a.T: # since no col in for loop, so we can use a transpose, row -> col
    print(col)

[14 15 16 17]
[18 19 20 21]
[22 23 24 25]
[26 27 28 29]

[14 18 22 26]
[15 19 23 27]
[16 20 24 28]
[17 21 25 29]


In [54]:
# output each element of matrix in a with loop
print(a)
print(a.flatten()) # return a copy of the array collapsed into one dimension
for element in a.flat: # or just a, .flat is a iterator, show 1 by 1
    print(element)

[[14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]]
[14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
