In [1]:
import numpy as np

In [2]:
# merge series
a = np.array([1, 1, 1]) # if want 1 x 3 matrix use np.array([[1,1,1]]), 
b = np.array([2, 2, 2]) # but now this is a series
print(a.shape)
print('')

# merge vertically, a top, b bot
c = np.vstack((a, b)) # stack vertically but now this is 2 x 3 matrix
print(c, c.shape) # so two series stack vertically will become matrix
print('')

# merge horizontally, a left, b right
d = np.hstack((a, b)) # stack horizontally and this is a series which has 6 elements
print(d, d.shape) # !!!! not matrix

(3,)

[[1 1 1]
 [2 2 2]] (2, 3)

[1 1 1 2 2 2] (6,)


In [3]:
# transfer a series to 1 x 3 matrix
print(a)
b = a[np.newaxis, :] # add a row dimension to the series to make it 1 x 3 matrix
print(b, b.shape)
print('')

# transfer a series to 3 x 1 matrix
c = a[:, np.newaxis] # add a col dimension to the series to make it 3 x 1 matrix
print(c, c.shape)


[1 1 1]
[[1 1 1]] (1, 3)

[[1]
 [1]
 [1]] (3, 1)


In [4]:
# merge matrix
a = np.array([1, 1, 1])[:,np.newaxis] # transfer a series to 1 x 3 matrix
b = np.array([2, 2, 2])[:,np.newaxis]
print(a)
print('')
print(b)
print('')

c = np.vstack((a,b)) # stack vertically, become 1 x 6 matrix
d = np.hstack((a,b)) # stack horizontally, become 3 x 2 matrix
print(c)
print('')
print(d)

[[1]
 [1]
 [1]]

[[2]
 [2]
 [2]]

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]

[[1 2]
 [1 2]
 [1 2]]


In [5]:
# merge multi array/matrix
a = np.array([1, 1, 1])[:,np.newaxis] # transfer a series to 1 x 3 matrix
b = np.array([2, 2, 2])[:,np.newaxis]

c = np.hstack((a,a,b,b,a,b))
# d = np.vstack((a,a,b,b,a,b))
print(c)

c = np.concatenate((a,a,b,b,a,b), axis = 1) # 1 row by row, 0 col by col
print(c)

[[1 1 2 2 1 2]
 [1 1 2 2 1 2]
 [1 1 2 2 1 2]]
[[1 1 2 2 1 2]
 [1 1 2 2 1 2]
 [1 1 2 2 1 2]]
