In [1]:
import numpy as np

In [62]:
a = np.arange(12).reshape(3, 4)
print(a)
print('')

# split 3 x 4 matrix to 2 pieces equally, col by col （controlling by axis)
b = np.split(a, 2, axis = 1) # or b = np.hsplit(a, 2)
c = np.split(a, 3, axis = 0) # or c = np.vsplit(a, 3)
print(b)
print(c)
print('')
# print(b[0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]



In [73]:
# not equally split
b = np.array_split(a, 2, axis = 0)
print(b)
print('')

b = np.array_split(a, 3, axis = 1)
print(b)

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
