In [1]:
import numpy as np

In [23]:
# array connection (connection will connect each other）
a = np.arange(4)
print(a)

b = a
c = a
d = b
a[0] = 11
d[1:3] = [22, 33]
print(b, c, d)
a is b

[0 1 2 3]
[11 22 33  3] [11 22 33  3] [11 22 33  3]


True

In [24]:
# array assignment （assignment is just the value get assigned)
A = np.arange(4)
print(A)

B = A.copy() # deep copy which the assignmenbt would not connect variables
A[3] = 44
print(A)
print(B)
A is B

[0 1 2 3]
[ 0  1  2 44]
[0 1 2 3]


False