In [1]:
# numpy, scipy, pandas
# numerical python, scientific python, pandas ...
# we processing data by storing in different format, 1D, 2D..., the data stored in these way can be done by 
# python is a dynamic language, which has only dynamic collection data type: double, set...
# becuase of numpy only, we can get arrays in python
import numpy as np

In [6]:
# creating an array
my_list = [10, 20, 30, 40, 50]
arr = np.array(my_list) # constructing array object
print(arr)

[10 20 30 40 50]


In [35]:
# in python, this is a list
a = [[1, 2, 3],
     [2, 3, 4]]
print(a)
print(type(a))

print('')
# by using np.array, the list can be transfered to 2D array
array = np.array(a)
print(array)
print(type(array))

[[1, 2, 3], [2, 3, 4]]
<class 'list'>

[[1 2 3]
 [2 3 4]]
<class 'numpy.ndarray'>


In [37]:
# array attribute
print('')

# number of array dimension
print('number of dimension:', array.ndim)

# tuple of array dimensions.
print('shape:', array.shape)

# number of elements in the array.
print('Size:', array.size)



number of dimension: 2
shape: (2, 3)
Size: 6
